# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ecd03d3145d98621671124eb9e8c3aa989dcd69bdf8d2d438bf9fb34f48be70fd3be167ee18b6280d30eaddfa7fe230078a7a7ce7748e03a0ddd12902ec5596

test:
  secret_key_base: e3cba9e1b8eb52410b9bfd834f74d6a80e3172f37404cc2f334f73f78c66fe9d1e8384bbb332944a61c48847c9ca60f9c19cd23df9418d0cb99a2254b82aaeb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
